import "./globals.css";
import Header from "../components/Header";
import EntrySection from "@/components/HomeEntrySection";
// import Footer from "../components/Footer";
import Blob from "../public/Blob.png";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Image src={Blob} className="circle right-bottom" />
        <Image src={Blob} className="circle left-bottom" />
        <Image src={Blob} className="circle top-center" />
        <div className="main-div">
          <Header />
          <EntrySection />
          {children}
        </div>
      </body>
    </html>
  );
}
