import "./globals.css";
import Header from "../components/Header";
import EntrySection from "@/components/HomeEntrySection";
// import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <EntrySection />
        {children}
      </body>
    </html>
  );
}
