import "./globals.css";
import Header from "../components/Header";
import EntrySection from "@/components/HomeEntrySection";
// import Footer from "../components/Footer";
import Blob from "../public/Blob.png";
import Image from "next/image";
import { ReduxProvider } from "@/redux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Image src={Blob} className="circle right-bottom" alt="blob" />
          <Image src={Blob} className="circle left-bottom" alt="blob" />
          <Image src={Blob} className="circle top-center" alt="blob" />
          <div className="main-div">
            <Header />
            <EntrySection />
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
